/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface AbstractProxyInterface extends ethers.utils.Interface {
  functions: {
    "getImplementationAuthority()": FunctionFragment;
    "setImplementationAuthority(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getImplementationAuthority",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setImplementationAuthority",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "getImplementationAuthority",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setImplementationAuthority",
    data: BytesLike
  ): Result;

  events: {
    "ImplementationAuthoritySet(address)": EventFragment;
    "Initialized(uint8)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ImplementationAuthoritySet"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Initialized"): EventFragment;
}

export class AbstractProxy extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: AbstractProxyInterface;

  functions: {
    getImplementationAuthority(overrides?: CallOverrides): Promise<[string]>;

    "getImplementationAuthority()"(
      overrides?: CallOverrides
    ): Promise<[string]>;

    setImplementationAuthority(
      _newImplementationAuthority: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "setImplementationAuthority(address)"(
      _newImplementationAuthority: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  getImplementationAuthority(overrides?: CallOverrides): Promise<string>;

  "getImplementationAuthority()"(overrides?: CallOverrides): Promise<string>;

  setImplementationAuthority(
    _newImplementationAuthority: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "setImplementationAuthority(address)"(
    _newImplementationAuthority: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    getImplementationAuthority(overrides?: CallOverrides): Promise<string>;

    "getImplementationAuthority()"(overrides?: CallOverrides): Promise<string>;

    setImplementationAuthority(
      _newImplementationAuthority: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "setImplementationAuthority(address)"(
      _newImplementationAuthority: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    ImplementationAuthoritySet(
      _implementationAuthority: string | null
    ): TypedEventFilter<[string], { _implementationAuthority: string }>;

    Initialized(version: null): TypedEventFilter<[number], { version: number }>;
  };

  estimateGas: {
    getImplementationAuthority(overrides?: CallOverrides): Promise<BigNumber>;

    "getImplementationAuthority()"(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setImplementationAuthority(
      _newImplementationAuthority: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "setImplementationAuthority(address)"(
      _newImplementationAuthority: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getImplementationAuthority(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getImplementationAuthority()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setImplementationAuthority(
      _newImplementationAuthority: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "setImplementationAuthority(address)"(
      _newImplementationAuthority: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
